name: Build AVR GCC

on:
  push:
  workflow_dispatch:

jobs:
  build-avr-gcc:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
         ls
         python3 get_avr_gcc.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: toolchain-avr-gcc
          path: toolchain-avr-gcc.tar.bz2

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: toolchain-avr-gcc.tar.bz2